name: Publish CLI to npm

on:
  push:
    tags:
      - "cli-v*.*.*" # e.g., cli-v1.2.3

jobs:
  publish:
    name: Publish CLI Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org/"
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install 

      - name: Build CLI (if using TypeScript)
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
